version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Stockholm
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
